#!/bin/bash

source /etc/update-motd.d/colors.txt

# Получаем описание ОС (например, Ubuntu 20.04.6 LTS)
os_desc=$(lsb_release -d | cut -f2-)

# Получаем версию ядра
kernel_ver=$(uname -r)

echo -e " ${TITLE_COLOR}OS and Kernel.......:${NC} ${TEXT_COLOR}${os_desc}, Kernel ${kernel_ver}${NC}"
echo -e " ${TITLE_COLOR}Last login..........:${NC} ${TEXT_COLOR}$(last | head -1 | cut -c 1-9 | xargs)${DEFAULT_COLOR} at ${TEXT_COLOR}$(last | head -1 | cut -c 40-55 | xargs)${DEFAULT_COLOR} from ${TEXT_COLOR}$(last | head -1 | cut -c 23-39 | xargs)${NC}"
