#!/bin/bash

source /etc/update-motd.d/colors.txt 2>/dev/null || true

echo -e " ${TITLE_COLOR}Load Averages.......:${DEFAULT_COLOR} 1 min: ${TEXT_COLOR}$(awk '{print $1}' /proc/loadavg)${DEFAULT_COLOR} | 5 mins: ${TEXT_COLOR}$(awk '{print $2}' /proc/loadavg)${DEFAULT_COLOR} | 15 mins: ${TEXT_COLOR}$(awk '{print $3}' /proc/loadavg)${NC}"
