#!/bin/bash

source /etc/update-motd.d/colors.txt 2>/dev/null || true

read -r LOAD1 LOAD5 LOAD15 _ _ < /proc/loadavg

echo -e " ${TITLE_COLOR}Load Averages.......:${DEFAULT_COLOR} 1 min: ${TEXT_COLOR}${LOAD1}${DEFAULT_COLOR} | 5 mins: ${TEXT_COLOR}${LOAD5}${DEFAULT_COLOR} | 15 mins: ${TEXT_COLOR}${LOAD15}${NC}"
