#!/bin/bash

source /etc/update-motd.d/colors.txt 2>/dev/null || true

read -r MEM_USED MEM_FREE MEM_TOTAL <<< "$(free -m | awk '/^Mem:/ {print $3, $7, $2}')"

echo -e " ${TITLE_COLOR}Memory..............:${DEFAULT_COLOR} Used: ${TEXT_COLOR}${MEM_USED}${DEFAULT_COLOR} MB | Free: ${TEXT_COLOR}${MEM_FREE}${DEFAULT_COLOR} MB | Total: ${TEXT_COLOR}${MEM_TOTAL}${DEFAULT_COLOR} MB${NC}"
